language: bash
services: docker

env:
  - VERSION=9.6 VERSION_MINOR=9.6.6
  - VERSION=9.5 VERSION_MINOR=9.5.10
  - VERSION=9.4 VERSION_MINOR=9.4.15
  - VERSION=9.3 VERSION_MINOR=9.3.20
  - VERSION=10 VERSION_MINOR=10.1

before_script:
  - env | sort
  - cd "$VERSION"
  - image="apsl/postgres:${VERSION_MINOR}"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      travis_retry docker build -t "$image" .
    )
after_script:
  - docker images

# vim:set et ts=2 sw=2:
